name: pre-commit

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v2.0.0
      with:
        extra_args: --all-files --hook-stage push
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        PYTHONPATH: "."
